### ISSUE TITLE
Chat cursor hotkey makes typing "/" impossible

### ISSUE THREAD

**Issue by weavejester** [farirpgs/fari-app#418]
## 🚩 Describe the bug

When I open up a character sheet and type in a text field, the "/" key will bring up the chat cursor instead of typing "/". This makes it very difficult to fill in some fields (e.g. character pronouns). Workaround is to type in a text editor and copy and paste into the character sheet.

The correct behavior is probably to disable the chat cursor hot key while filling in a text field. Or if the user has a character sheet open at all, as the chat cursor appears *behind* the character sheet.

## 🔢 Steps to reproduce

Open up a character sheet with a text field.
Select a text field.
Type "They/Them".

## 🟢 Expected behavior

The text field contains "They/Them"

## 🔴 Actual behavior

The text field contains "They" and a chat cursor appears behind the character sheet with the word "Them".

## 💅 Screenshots

![image](https://user-images.githubusercontent.com/8780/180303623-e66c01e9-9aa7-411e-9dd7-143f7d6f6be3.png)

## 🖥 Desktop or Smartphone

- OS: Windows 10
- Browser: Chrome (also tested on Firefox)
- Device: PC

**Comment by glmdgrielson** [comment]
Double checking this bug and I'm not seeing it?

**Comment by weavejester** [comment]
It looks like this has been fixed since it was reported. I no longer get this bug when testing.
